backend:
  replicaCount: 2
  resources:
    limits:
      cpu: 400m
      memory: 128Mi
    requests:
      cpu: 150m
      memory: 64Mi

frontend:
  replicaCount: 1
  resources:
    limits:
      cpu: 400m
      memory: 128Mi
    requests:
      cpu: 150m
      memory: 64Mi
