apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polar-backend-app
  name: polar-backend-app
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: polar-backend-app
  template: 
    metadata:
      labels:
        app: polar-backend-app
    spec:
      containers:
      - image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        name: polar-backend-app
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports: 
        - containerPort: {{ .Values.backend.service.targetPort }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}