apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polar-react-app
  name: polar-react-app
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: polar-react-app
  template:
    metadata:
      labels:
        app: polar-react-app
    spec:
      containers:
      - image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        name: polar-react-app
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports: 
        - containerPort: {{ .Values.frontend.service.targetPort }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
