apiVersion: v1
kind: Service
metadata:
  labels:
    app: polar-react-app
  name: polar-react-app-service
spec:
  ports:
  - port: {{ .Values.frontend.service.port }}
    protocol: TCP
    targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: polar-react-app
  type: {{ .Values.frontend.service.type }}
