apiVersion: v1
kind: Service
metadata:
  labels:
    app: polar-app
  name: polar-app-service
spec:
  ports:
  - port: {{ .Values.backend.service.port }}
    protocol: TCP
    targetPort: {{ .Values.backend.service.targetPort }}
  selector:
    app: polar-backend-app
  type: {{ .Values.backend.service.type }}